version: '2'
services:
  thresher_api:
    # python:2.7-slim installs postgres 9.4 client
    depends_on:
      - db
      - django_rq
    build:
      context: .
      dockerfile: ./docker/thresher_api/Dockerfile
    ports:
      - "5000:5000"

  import_export_worker:
    # Same image as thresher_api
    # Runs the queue for importing articles and schemas and exporting projects and tasks
    depends_on:
      - django_rq
    build:
      context: .
      dockerfile: ./docker/thresher_api/Dockerfile
    command: ["python", "data/rqworker.py"]

  nlp_hints:
    image: teamforecast/nlp_hints:latest
    depends_on:
      - django_rq

  django_rq:
    image: redis:3.2.9

  pybossa:
    # ubuntu:14.04 installs postgres 9.4 client
    image: teamforecast/pybossa:latest
    depends_on:
      - db
    ports:
      - "3002:80"

  db:
    # postgres:9.4
    build:
      context: ./docker
      dockerfile: ./db/Dockerfile
#   volumes:
#    - ./_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=zz
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=thresher
#    - PGDATA=/var/lib/postgresql/data/pgdata
