version: '2'
services:
  thresher_api:
    # python:2.7-slim installs postgres 9.4 client
    depends_on:
      - db
      - django_rq
    build:
      context: ./docker
      dockerfile: ./thresher_api/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/home/thresher

  import_export_worker:
    # Same image as thresher_api
    # Runs the queue for importing articles and schemas and exporting projects and tasks
    depends_on:
      - django_rq
    build:
      context: ./docker
      dockerfile: ./thresher_api/Dockerfile
    volumes:
      - .:/home/thresher
    environment:
      PYTHONPATH: /home/thresher
    command: ["python", "data/rqworker.py"]

  nlp_hints:
    image: teamforecast/nlp_hints:latest
    depends_on:
      - django_rq

  django_rq:
    image: redis:3.2.8

  pybossa:
    # ubuntu:14.04 installs postgres 9.4 client
    depends_on:
      - db
    build:
      context: ./docker
      dockerfile: ./pybossa/Dockerfile
    ports:
      - "3002:80"

  db:
    # postgres:9.4
    build:
      context: ./docker
      dockerfile: ./db/Dockerfile
#   volumes:
#    - ./_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=zz
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=thresher
#    - PGDATA=/var/lib/postgresql/data/pgdata
