# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 03:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_number', models.IntegerField()),
                ('answer_content', models.TextField()),
                ('next_questions', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.IntegerField(null=True)),
                ('text', models.TextField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='ArticleHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pybossa_id', models.IntegerField(db_index=True, null=True)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_taskruns', to='thresher.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pybossa_user_id', models.IntegerField(db_index=True, null=True, unique=True)),
                ('experience_score', models.FloatField()),
                ('accuracy_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HighlightGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offsets', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('case_number', models.IntegerField(db_index=True)),
                ('article_highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='thresher.ArticleHighlight')),
            ],
        ),
        migrations.CreateModel(
            name='NLPHints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_type', models.CharField(choices=[(b'NONE', b'No hint'), (b'WHERE', b'Where'), (b'WHO', b'Who'), (b'HOW MANY', b'How many'), (b'WHEN', b'When')], max_length=10)),
                ('offsets', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='thresher.Article')),
            ],
            options={
                'verbose_name': 'NLP hint',
                'verbose_name_plural': 'NLP hints',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('task_type', models.CharField(choices=[(b'HLTR', b'Highlighter'), (b'QUIZ', b'Quiz')], default=b'HLTR', max_length=4)),
                ('pybossa_url', models.URLField(blank=True, default=b'')),
                ('pybossa_id', models.IntegerField(null=True)),
                ('pybossa_owner_id', models.IntegerField(null=True)),
                ('pybossa_secret_key', models.CharField(blank=True, default=b'', max_length=36)),
                ('pybossa_created', models.DateTimeField(null=True)),
                ('pybossa_project_password', models.CharField(blank=True, default=b'', max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[(b'RADIO', b'Single answer - radio buttons'), (b'CHECKBOX', b'Multiple answer - checkboxes'), (b'DATETIME', b'Date and Time'), (b'DATE', b'Date only'), (b'TIME', b'Time only'), (b'TEXT', b'Text')], max_length=10)),
                ('hint_type', models.CharField(choices=[(b'NONE', b'No hint'), (b'WHERE', b'Where'), (b'WHO', b'Who'), (b'HOW MANY', b'How many'), (b'WHEN', b'When')], default=b'NONE', max_length=10)),
                ('next_questions', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='QuizTaskRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pybossa_id', models.IntegerField(db_index=True, null=True)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_taskruns', to='thresher.Contributor')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('offsets', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('highlight_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_answers', to='thresher.HighlightGroup')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_answers', to='thresher.Question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_answers', to='thresher.QuizTaskRun')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=4)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('pybossa_id', models.IntegerField()),
                ('pybossa_project_id', models.IntegerField()),
                ('pybossa_created', models.DateTimeField()),
                ('pybossa_state', models.CharField(max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='thresher.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('order', models.IntegerField(null=True)),
                ('glossary', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('instructions', models.TextField()),
                ('hint_type', models.CharField(choices=[(b'NONE', b'No hint'), (b'WHERE', b'Where'), (b'WHO', b'Who'), (b'HOW MANY', b'How many'), (b'WHEN', b'When')], default=b'NONE', max_length=10)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subtopics', to='thresher.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pybossa_url', models.CharField(blank=True, default=b'', max_length=200)),
                ('pybossa_api_key', models.CharField(blank=True, default=b'', max_length=36)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quiztaskrun',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_taskruns', to='thresher.Task'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='thresher.Topic'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='thresher.UserProfile'),
        ),
        migrations.AddField(
            model_name='highlightgroup',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='highlights', to='thresher.Topic'),
        ),
        migrations.AddField(
            model_name='articlehighlight',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlight_taskruns', to='thresher.Contributor'),
        ),
        migrations.AddField(
            model_name='articlehighlight',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlight_taskruns', to='thresher.Task'),
        ),
        migrations.AddField(
            model_name='articlehighlight',
            name='topics_identified',
            field=models.ManyToManyField(through='thresher.HighlightGroup', to='thresher.Topic'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='thresher.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('parent', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('topic', 'question_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='nlphints',
            unique_together=set([('article', 'hint_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('question', 'answer_number')]),
        ),
    ]
