# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 02:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.IntegerField()),
                ('answer_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date_published', models.DateField(null=True)),
                ('city_published', models.CharField(max_length=1000)),
                ('state_published', models.CharField(max_length=2, null=True)),
                ('periodical', models.CharField(max_length=1000)),
                ('periodical_code', models.IntegerField()),
                ('parse_version', models.CharField(max_length=5, null=True)),
                ('annotators', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_groups', to='thresher.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HighlightGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offsets', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_text', models.TextField()),
                ('contingency', models.BooleanField(default=False)),
                ('default_next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_default', to='thresher.Question')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('highlight_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_answer', to='thresher.HighlightGroup')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thresher.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('order', models.IntegerField(null=True)),
                ('glossary', models.TextField()),
                ('instructions', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='thresher.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_score', models.DecimalField(decimal_places=3, max_digits=5)),
                ('accuracy_score', models.DecimalField(decimal_places=3, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='submittedanswer',
            name='user_submitted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_answer', to='thresher.UserProfile'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_questions', to='thresher.Topic'),
        ),
        migrations.AddField(
            model_name='client',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='thresher.Topic'),
        ),
        migrations.AddField(
            model_name='articlehighlight',
            name='highlight',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thresher.HighlightGroup'),
        ),
        migrations.AddField(
            model_name='articlehighlight',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_highlight', to='thresher.Topic'),
        ),
        migrations.AddField(
            model_name='answer',
            name='next_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_question', to='thresher.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='thresher.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('parent', 'order', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('topic', 'question_text')]),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('answer_id', 'question')]),
        ),
    ]
