# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pybossa_url',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
