# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
