# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0002_auto_20161020_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_id',
            new_name='answer_number',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_id',
            new_name='question_number',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_id',
        ),
        migrations.AddField(
            model_name='article',
            name='article_number',
            field=models.IntegerField(null=True),
        ),
        # migrations.AddField(
        #     model_name='article',
        #     name='id',
        #     field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
        #     # Django asks me to create a default=0 in field, which is weird.
        #     # With this default Django will not be able to create auto field
        #     # because of "multiple defaults specified"
        #     preserve_default=False,
        # ),
        migrations.DeleteModel(name='Article'),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.IntegerField(null=True)),
                ('text', models.TextField()),
                ('date_published', models.DateField(null=True)),
                ('city_published', models.CharField(max_length=1000)),
                ('state_published', models.CharField(max_length=2, null=True)),
                ('periodical', models.CharField(max_length=1000)),
                ('periodical_code', models.IntegerField()),
                ('parse_version', models.CharField(max_length=5, null=True)),
                ('annotators', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('answer_number', 'question')]),
        ),
    ]
