# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0002_auto_20170607_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[(b'RADIO', b'Single answer - radio buttons'), (b'CHECKBOX', b'Multiple answer - checkboxes'), (b'TEXT', b'Text'), (b'DATE', b'Date'), (b'TIME', b'Time')], max_length=10),
        ),
    ]
