# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 03:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0003_auto_20170622_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='instructions',
            new_name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='pybossa_api_key',
            field=models.CharField(blank=True, default=b'', max_length=36),
        ),
        migrations.AddField(
            model_name='project',
            name='task_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
