# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0004_auto_20161110_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[(b'RADIO', b'Single answer - radio buttons'), (b'CHECKBOX', b'Multiple answer - checkboxes'), (b'DATETIME', b'Date Time'), (b'TEXT', b'Text')], max_length=10),
        ),
    ]
