# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0004_auto_20161028_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightgroup',
            name='article_highlight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='thresher.ArticleHighlight'),
        ),
    ]
