# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0004_auto_20170712_0316'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('short_name', 'pybossa_url'), ('name', 'pybossa_url')]),
        ),
    ]
