# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0004_auto_20161028_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='question_type',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('topic', 'question_text')]),
        ),
    ]
