# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0005_auto_20161028_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlehighlight',
            name='topic',
        ),
        migrations.AddField(
            model_name='highlightgroup',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_highlights', to='thresher.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('parent', 'name')]),
        ),
    ]
