# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0005_auto_20170714_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='submittedanswer',
            name='highlight_group',
        ),
        migrations.RemoveField(
            model_name='submittedanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='hint_type',
        ),
        migrations.AddField(
            model_name='quiztaskrun',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_taskruns', to='thresher.Article'),
        ),
        migrations.AddField(
            model_name='quiztaskrun',
            name='highlight_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_answers', to='thresher.HighlightGroup'),
        ),
        migrations.AddField(
            model_name='submittedanswer',
            name='answer_text',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='accuracy_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='experience_score',
            field=models.FloatField(default=0.0),
        ),
    ]
