# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0005_auto_20161111_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlehighlight',
            name='topics_identified',
            field=models.ManyToManyField(through='thresher.HighlightGroup', to='thresher.Topic'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='next_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_next', to='thresher.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='thresher.Question'),
        ),
        migrations.AlterField(
            model_name='articlehighlight',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_highlights', to='thresher.Article'),
        ),
        migrations.AlterField(
            model_name='articlehighlight',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_highlights', to='thresher.UserProfile'),
        ),
        migrations.AlterField(
            model_name='highlightgroup',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='highlights', to='thresher.Topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='default_next',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_default', to='thresher.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='thresher.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtopics', to='thresher.Topic'),
        ),
    ]
