# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0007_auto_20170211_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pybossa_api_key',
            field=models.CharField(default=b'', max_length=36),
        ),
    ]
