# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0007_submittedanswer_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedanswer',
            old_name='quiz',
            new_name='quiz_task_run',
        ),
    ]
