# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0008_auto_20170821_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedanswer',
            name='answer',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_answers', to='thresher.Answer'),
        ),
    ]
