# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0008_auto_20170210_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pybossa_url',
            field=models.URLField(default=b''),
        ),
    ]
