# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0009_userprofile_pybossa_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pybossa_api_key',
            field=models.CharField(blank=True, default=b'', max_length=36),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pybossa_url',
            field=models.URLField(blank=True, default=b''),
        ),
    ]
