# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0009_auto_20170821_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaskrun',
            name='highlight_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_taskruns', to='thresher.HighlightGroup'),
        ),
    ]
