# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0010_auto_20170822_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('errtype', models.TextField()),
                ('file_name', models.TextField()),
                ('linenum', models.IntegerField()),
            ],
        ),
    ]
