# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0010_auto_20170222_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightgroup',
            name='case_number',
            field=models.IntegerField(db_index=True),
        ),
    ]
