# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0011_auto_20170224_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=16)),
                ('components', django.contrib.postgres.fields.jsonb.JSONField(default={b'task_type': b''})),
                ('pybossa_id', models.IntegerField()),
                ('pybossa_project_id', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('state', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='pybossa_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='task_type',
            field=models.CharField(choices=[(b'HLTR', b'Highlighter'), (b'QUIZ', b'Quiz')], default=b'HLTR', max_length=4),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='thresher.Project'),
        ),
    ]
