# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0011_parsererror'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsererror',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
