# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0012_parsererror_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='username',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=set([('username', 'pybossa_user_id')]),
        ),
    ]
