# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 00:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0013_auto_20170227_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='pybossa_created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='state',
            new_name='pybossa_state',
        ),
        migrations.RemoveField(
            model_name='task',
            name='components',
        ),
        migrations.AddField(
            model_name='task',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(max_length=4),
        ),
    ]
