# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0014_auto_20170228_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pybossa_url',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
