# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 07:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0015_auto_20171024_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
