# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0016_auto_20170313_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLPHints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_text', models.TextField()),
                ('offsets', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='thresher.Article')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='thresher.Question')),
            ],
        ),
    ]
