# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0018_auto_20170321_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlehighlight',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_highlights', to='thresher.Task'),
        ),
    ]
