# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0019_articlehighlight_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlehighlight',
            name='pybossa_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
