# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 00:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thresher', '0020_articlehighlight_pybossa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='contingency',
        ),
        migrations.RemoveField(
            model_name='question',
            name='default_next',
        ),
        migrations.AddField(
            model_name='question',
            name='next_questions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
